### PR TITLE
Fix api_call since slack_web params changed

### PR DESCRIPTION
**Pull request by pdkhai**

### CODE REVIEW

**Comment by nzlosh** [comment]
This PR will break code that is passing data through to the underlying slack-sdk module.  `**data` is to allow plugin developers to pass keyword arguments to slack-sdk function calls to match the function signature.

**Comment by pdkhai** [comment]
@nzlosh please review again.

**Comment by nzlosh** [comment]
The latest commit looks good to me.  Would you mind adding an entry to the changelog please so I can go ahead and merge this PR?

**Comment by nzlosh** [comment]
Thank you for the fix @pdkhai

**Pull request merged**
